#!/usr/bin/env python3
"""Builds results/cloud/CLOUD_TABLES.md from the cloud experiment CSVs (all SIMULATED evidence).

Usage (from spikes/physical_link_lab): python3 scripts/cloud_tables.py [--cloud results/cloud]
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def md(df: pd.DataFrame, digits: int = 2) -> str:
    if df is None or df.empty:
        return "_no data_\n"
    df = df.copy()
    cols = [str(c) for c in df.columns]
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        cells = []
        for v in r.values:
            if isinstance(v, float):
                cells.append("" if v != v else f"{v:.{digits}f}")
            else:
                cells.append(str(v))
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cloud", type=Path, default=Path("results/cloud"))
    a = ap.parse_args()
    c = a.cloud
    parts = ["# Cloud evidence tables (generated by scripts/cloud_tables.py — SIMULATED, not physical)\n"]

    f = c / "fountain_bench.csv"
    if f.exists():
        d = pd.read_csv(f)
        parts.append("\n## Fountain / erasure benchmark (20% random erasure, shuffled, symbol 1000 B, desktop JVM)\n\n")
        parts.append(md(d[["variant", "payload_bytes", "K", "trials", "encode_MBps", "decode_MBps", "overhead_p50",
                           "overhead_p90", "overhead_max", "fail_at_K", "fail_at_K2", "decoder_heap_MB"]], 3))

    f = c / "loss_bench.csv"
    if f.exists():
        d = pd.read_csv(f)
        parts.append("\n## Frame-loss channel (256 KB object, K = 263): efficiency = K / frames sent (median)\n\n")
        pv = d.pivot_table(index="channel", columns="variant", values="efficiency_p50").reset_index()
        ideal = d.groupby("channel")["ideal_efficiency"].first().reset_index()
        parts.append(md(pv.merge(ideal, on="channel"), 3))

    f = c / "timing_sweep.csv"
    if f.exists():
        d = pd.read_csv(f)
        for exp in (8.0, 1.0):
            sel = d[(d.exposure_ms == exp) & (d.readout_ms == 25) & (d.perpendicular) & (d.response_ms == 0.5) & (d.tiles == 1)]
            pv = sel.pivot_table(index="tx_fps", columns=["refresh_hz", "camera_fps"], values="unique_symbols_per_s")
            pv.columns = [f"{int(h)}Hz/{int(cam)}fps" for h, cam in pv.columns]
            parts.append(f"\n## Timing model: distinct clean symbols/s (exposure {exp:g} ms, readout 25 ms, OLED, both portrait)\n\n")
            parts.append(md(pv.reset_index(), 1))
        sel = d[(d.exposure_ms == 8) & (d.readout_ms == 25) & (d.perpendicular) & (d.response_ms == 0.5) & (d.tiles == 1)]
        pv = sel.pivot_table(index="tx_fps", columns=["refresh_hz", "camera_fps"], values="worst_phase_symbols_per_s")
        pv.columns = [f"{int(h)}Hz/{int(cam)}fps" for h, cam in pv.columns]
        parts.append("\n## Timing model: worst display/camera phase (exposure 8 ms)\n\n" + md(pv.reset_index(), 1))
        sel = d[(d.exposure_ms == 8) & (d.readout_ms == 25) & (~d.perpendicular) & (d.response_ms == 0.5) & (d.refresh_hz == 60) & (d.camera_fps == 30)]
        pv = sel.pivot_table(index="tx_fps", columns="tiles", values="unique_tile_symbols_per_s")
        parts.append("\n## Rolling-shutter tiling (parallel scan, 60 Hz / 30 fps, exposure 8 ms): symbol-equivalents/s by tiles\n\n" + md(pv.reset_index(), 1))

    f = c / "camsim_sweep.csv"
    if f.exists():
        d = pd.read_csv(f)
        dist = d[d.group == "distance"]
        for res in ("1280x720", "1920x1080", "3840x2160"):
            s = dist[dist.analysis_res == res]
            if s.empty:
                continue
            pv = s.pivot_table(index="config", columns="distance_cm", values="success_rate")
            pv.columns = [f"{int(x)} cm" for x in pv.columns]
            parts.append(f"\n## Camera simulator: decode success vs distance ({res}, 1×, INDOOR_NORMAL)\n\n" + md(pv.reset_index(), 2))
        s = dist[dist.analysis_res == "1920x1080"]
        pv = s.pivot_table(index="config", columns="distance_cm", values="predicted_goodput_KBps_at_15fps")
        pv.columns = [f"{int(x)} cm" for x in pv.columns]
        cap = d.groupby("config")["capacity_bytes"].first()
        pv.insert(0, "frame_bytes", cap.reindex(pv.index).values)
        parts.append("\n## Model goodput (KB/s) = success × (frame − 19 B) × 15 fps × 0.97 (1080p)\n\n" + md(pv.reset_index(), 2))
        pm = s.pivot_table(index="config", columns="distance_cm", values="px_per_module")
        pm.columns = [f"{int(x)} cm" for x in pm.columns]
        parts.append("\n## Camera pixels per module/cell (1080p, 1×)\n\n" + md(pm.reset_index(), 1))
        other = d[d.group != "distance"].copy()
        other["cond"] = other["group"] + other.apply(
            lambda r: {"angle": f"_{int(r.angle_deg)}", "light": f"_{r.light}", "motion": f"_{r.motion_blur_px:g}px",
                       "jpeg": f"_q{int(r.jpeg_q) if r.jpeg_q == r.jpeg_q else 0}", "zoom2x": f"_{int(r.distance_cm)}cm"}.get(r.group, ""), axis=1)
        pv = other.pivot_table(index="config", columns="cond", values="success_rate")
        parts.append("\n## Camera simulator: robustness at 40 cm (1080p) — success rate\n\n" + md(pv.reset_index(), 2))
        lat = d.groupby("codec")["decode_ms_p50_jvm"].describe()[["count", "50%", "75%", "max"]]
        parts.append("\n## Decode latency on the cloud JVM (ms per frame, all simulated frames)\n\n" + md(lat.reset_index(), 1))

    f = c / "veil_sweep.csv"
    if f.exists():
        d = pd.read_csv(f)
        pv = d.pivot_table(index=["channel", "block_px", "distance_cm", "exposure_mix"], columns="delta_levels", values="ber")
        pv.columns = [f"Δ={c}" for c in pv.columns]
        parts.append("\n## Quasi-invisible complementary frames: BER (exposure_mix = share of the other frame in one exposure)\n\n" + md(pv.reset_index(), 3))
        ps = d.groupby(["channel", "delta_levels"])["psnr_single_frame_db"].mean().unstack()
        ps.columns = [f"Δ={c}" for c in ps.columns]
        parts.append("\n## Single-frame PSNR vs original image (dB)\n\n" + md(ps.reset_index(), 1))

    f = c / "pipeline_bench.csv"
    if f.exists():
        parts.append("\n## Receiver pipeline stages on the cloud JVM (ms, 25 cm)\n\n" + md(pd.read_csv(f), 2))

    vd = c / "virtual"
    rows = []
    for runs in sorted(vd.rglob("runs.csv")) if vd.exists() else []:
        r = pd.read_csv(runs)
        rows.append(r[["session_id", "distance_cm", "visual_key", "scheme", "payload_bytes", "RESULT", "goodput_bytes_sec",
                       "partial_goodput_bytes_sec" if "partial_goodput_bytes_sec" in r.columns else "goodput_bytes_sec",
                       "frames_seen", "frames_decoded", "symbols_unique", "source_symbols", "ghost_packets_identical", "ghost_packets_total"]])
    if rows:
        v = pd.concat(rows)
        v["goodput_KBps"] = v["goodput_bytes_sec"] / 1024
        parts.append("\n## Virtual end-to-end loop (TransmitterSession → display/camera timing → camera simulator → ReceiverSession)\n\n")
        parts.append(md(v.drop(columns=["goodput_bytes_sec"]), 2))

    out = c / "CLOUD_TABLES.md"
    out.write_text("".join(parts))
    print(f"wrote {out} ({sum(len(p) for p in parts)} chars)")


if __name__ == "__main__":
    main()
